//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoPB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoSoPB()
        {
            this.BanDoPhanBo = new HashSet<BanDoPhanBo>();
            this.PhanBon = new HashSet<PhanBon>();
            this.ThuocBVTV = new HashSet<ThuocBVTV>();
        }
    
        public int MaCoSo { get; set; }
        public string TenCoSo { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayCapGiayPhep { get; set; }
        public Nullable<int> LoaiCoSoID { get; set; }
        public string MaHanhChinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanDoPhanBo> BanDoPhanBo { get; set; }
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        public virtual DonViHanhChinh DonViHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanBon> PhanBon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuocBVTV> ThuocBVTV { get; set; }
    }
}
