//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViHanhChinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViHanhChinh()
        {
            this.CoSoATTP = new HashSet<CoSoATTP>();
            this.CoSoPB = new HashSet<CoSoPB>();
            this.CoSoThuocBVTV = new HashSet<CoSoThuocBVTV>();
            this.DonViHanhChinh1 = new HashSet<DonViHanhChinh>();
            this.NguoiDung = new HashSet<NguoiDung>();
            this.VungTrong = new HashSet<VungTrong>();
        }
    
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public int CapDoID { get; set; }
        public string CapTrenID { get; set; }
    
        public virtual CapDoHanhChinh CapDoHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoATTP> CoSoATTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoPB> CoSoPB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoThuocBVTV> CoSoThuocBVTV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonViHanhChinh> DonViHanhChinh1 { get; set; }
        public virtual DonViHanhChinh DonViHanhChinh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VungTrong> VungTrong { get; set; }
    }
}
