//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using adc.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DonViHanhChinh: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViHanhChinh()
        {
            this.CoSoATTP = new HashSet<CoSoATTP>();
            this.CoSoPB = new HashSet<CoSoPB>();
            this.CoSoThuocBVTV = new HashSet<CoSoThuocBVTV>();
            this.DonViHanhChinh1 = new HashSet<DonViHanhChinh>();
            this.NguoiDung = new HashSet<NguoiDung>();
            this.VungTrong = new HashSet<VungTrong>();
        }

        private string _MaDonVi;
        public string MaDonVi { get => _MaDonVi; set { _MaDonVi = value; OnPropertyChanged(); } }
        private string _TenDonVi;
        public string TenDonVi { get => _TenDonVi; set { _TenDonVi = value; OnPropertyChanged(); } }
        private int _CapDoID;
        public int CapDoID { get => _CapDoID; set { _CapDoID = value; OnPropertyChanged(); } }
        private string _CapTrenID;
        public string CapTrenID { get => _CapTrenID; set { _CapTrenID = value; OnPropertyChanged(); } }

        public virtual CapDoHanhChinh CapDoHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoATTP> CoSoATTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoPB> CoSoPB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSoThuocBVTV> CoSoThuocBVTV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonViHanhChinh> DonViHanhChinh1 { get; set; }
        public virtual DonViHanhChinh DonViHanhChinh2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VungTrong> VungTrong { get; set; }
    }
}
