//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiongCayTrong
    {
        public int MaCayTrong { get; set; }
        public string TenGiongCay { get; set; }
        public Nullable<int> LoaiCayTrongID { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> VungTrongID { get; set; }
    
        public virtual LoaiCayTrong LoaiCayTrong { get; set; }
        public virtual VungTrong VungTrong { get; set; }
    }
}
