//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTrongTrotEntities1 : DbContext
    {
        public QuanLyTrongTrotEntities1()
            : base("name=QuanLyTrongTrotEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanDoPhanBo> BanDoPhanBoes { get; set; }
        public virtual DbSet<CapDoHanhChinh> CapDoHanhChinhs { get; set; }
        public virtual DbSet<CoSo> CoSoes { get; set; }
        public virtual DbSet<CoSoATTP> CoSoATTPs { get; set; }
        public virtual DbSet<CoSoPB> CoSoPBs { get; set; }
        public virtual DbSet<CoSoThuocBVTV> CoSoThuocBVTVs { get; set; }
        public virtual DbSet<DonViHanhChinh> DonViHanhChinhs { get; set; }
        public virtual DbSet<GiongCayTrong> GiongCayTrongs { get; set; }
        public virtual DbSet<LichSuTruyCap> LichSuTruyCaps { get; set; }
        public virtual DbSet<LoaiCayTrong> LoaiCayTrongs { get; set; }
        public virtual DbSet<LoaiCoSo> LoaiCoSoes { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhanBon> PhanBons { get; set; }
        public virtual DbSet<SinhVatGayHaiVaTuoiSau> SinhVatGayHaiVaTuoiSaus { get; set; }
        public virtual DbSet<ThuocBVTV> ThuocBVTVs { get; set; }
        public virtual DbSet<VaiTro> VaiTroes { get; set; }
        public virtual DbSet<VungTrong> VungTrongs { get; set; }
    }
}
