//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTrongTrotEntities : DbContext
    {
        public QuanLyTrongTrotEntities()
            : base("name=QuanLyTrongTrotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanDoPhanBo> BanDoPhanBo { get; set; }
        public virtual DbSet<CapDoHanhChinh> CapDoHanhChinh { get; set; }
        public virtual DbSet<CoSoATTP> CoSoATTP { get; set; }
        public virtual DbSet<CoSoPB> CoSoPB { get; set; }
        public virtual DbSet<CoSoThuocBVTV> CoSoThuocBVTV { get; set; }
        public virtual DbSet<DonViHanhChinh> DonViHanhChinh { get; set; }
        public virtual DbSet<GiongCayTrong> GiongCayTrong { get; set; }
        public virtual DbSet<LichSuTruyCap> LichSuTruyCap { get; set; }
        public virtual DbSet<LoaiCayTrong> LoaiCayTrong { get; set; }
        public virtual DbSet<LoaiCoSo> LoaiCoSo { get; set; }
        public virtual DbSet<NguoiDung> NguoiDung { get; set; }
        public virtual DbSet<PhanBon> PhanBon { get; set; }
        public virtual DbSet<SinhVatGayHaiVaTuoiSau> SinhVatGayHaiVaTuoiSau { get; set; }
        public virtual DbSet<ThuocBVTV> ThuocBVTV { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
        public virtual DbSet<VungTrong> VungTrong { get; set; }
    }
}
