//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using adc.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.LichSuTruyCap = new HashSet<LichSuTruyCap>();
        }
        public int ID { get; set; }
        private string _TenNguoiDung;
        public string TenNguoiDung { get => _TenNguoiDung; set { _TenNguoiDung = value; OnPropertyChanged(); } }
        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }
        private string _MatKhau;
        public string MatKhau { get => _MatKhau; set { _MatKhau = value; OnPropertyChanged(); } }
        private Nullable<int> _VaiTroID;
        public Nullable<int> VaiTroID { get => _VaiTroID; set { _VaiTroID = value; OnPropertyChanged(); } }
        private byte _TrangThai;
        public byte TrangThai { get => _TrangThai; set { _TrangThai = value; OnPropertyChanged(); } }
        private string _DonViHanhChinhID;
        public string DonViHanhChinhID { get => _DonViHanhChinhID; set { _DonViHanhChinhID = value; OnPropertyChanged(); } }

        public virtual DonViHanhChinh DonViHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTruyCap> LichSuTruyCap { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
