//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoLieuThongKe
    {
        public int ID { get; set; }
        public Nullable<int> CoSoID { get; set; }
        public Nullable<int> PhanBonID { get; set; }
        public Nullable<int> GiongCayID { get; set; }
        public Nullable<int> VungTrongID { get; set; }
        public Nullable<int> ThuocBVTVID { get; set; }
        public Nullable<int> SinhVatGayHaiVaTuoiSauID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> ThoiGianThongKe { get; set; }
    
        public virtual CoSo CoSo { get; set; }
        public virtual GiongCayTrong GiongCayTrong { get; set; }
        public virtual PhanBon PhanBon { get; set; }
        public virtual SinhVatGayHaiVaTuoiSau SinhVatGayHaiVaTuoiSau { get; set; }
        public virtual ThuocBVTV ThuocBVTV { get; set; }
        public virtual VungTrong VungTrong { get; set; }
    }
}
