//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VungTrong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VungTrong()
        {
            this.BanDoPhanBoes = new HashSet<BanDoPhanBo>();
            this.GiongCayTrongs = new HashSet<GiongCayTrong>();
            this.SinhVatGayHaiVaTuoiSaus = new HashSet<SinhVatGayHaiVaTuoiSau>();
        }
    
        public int ID { get; set; }
        public string TenVungTrong { get; set; }
        public string MoTa { get; set; }
        public string MaVungTrongID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanDoPhanBo> BanDoPhanBoes { get; set; }
        public virtual DonViHanhChinh DonViHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiongCayTrong> GiongCayTrongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVatGayHaiVaTuoiSau> SinhVatGayHaiVaTuoiSaus { get; set; }
    }
}
