//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adc.Model
{
    using adc.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class VungTrong:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VungTrong()
        {
            this.GiongCayTrong = new HashSet<GiongCayTrong>();
            this.SinhVatGayHaiVaTuoiSau = new HashSet<SinhVatGayHaiVaTuoiSau>();
        }

        private int _ID;
        public int ID { get => _ID; set { _ID = value; OnPropertyChanged(); } }
        private string _TenVungTrong;
        public string TenVungTrong { get => _TenVungTrong; set { _TenVungTrong = value; OnPropertyChanged(); } }
        private string _MoTa;
        public string MoTa { get => _MoTa; set { _MoTa = value; OnPropertyChanged(); } }
        private string _MaVungTrongID;
        public string MaVungTrongID { get => _MaVungTrongID; set { _MaVungTrongID = value; OnPropertyChanged(); } }

        public virtual DonViHanhChinh DonViHanhChinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiongCayTrong> GiongCayTrong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVatGayHaiVaTuoiSau> SinhVatGayHaiVaTuoiSau { get; set; }
    }
}
